Add EliiseS/devcontainer features to the list
devcontainers/devcontainers.github.io pull request #124
Opened 2023-01-06 11:48 UTC by EliiseS

2023-01-06 17:38 UTC, samruddhikhandale requested changes
Thanks, left one comment.

2023-01-06 17:38 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/EliiseS/devcontainer-features
```suggestion
  ociReference: ghcr.io/eliises/devcontainer-features
```

The ghcr packages supports lower casing, see here --> https://github.com/EliiseS/devcontainer-features/pkgs/container/devcontainer-features%2Fbash-profile


![image](https://user-images.githubusercontent.com/24955913/211067299-61a0ba95-e9af-43ff-ac08-9c77ac374a05.png)

2023-01-09 09:05 UTC, EliiseS commented on _data/collection-index.yml
> +  ociReference: ghcr.io/EliiseS/devcontainer-features
Thanks! Committed your suggestion 😄

2023-01-09 17:40 UTC, samruddhikhandale approved these changes
Awesome, thanks!

2023-01-09 17:42 UTC, merged