Update collection-index.yml
devcontainers/devcontainers.github.io pull request #131
Opened 2023-01-11 04:11 UTC by ChristopherMacGown

This PR adds my feature repository which provides maintained [mcfly](https://github.com/cantino/mcfly) and [direnv](https://github.com/direnv/direnv) as devcontainer features.

2023-01-11 17:25 UTC, samruddhikhandale requested changes
Thanks, added one comment.

2023-01-11 17:25 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/ChristopherMacGown/devcontainer-features
```suggestion
  ociReference: ghcr.io/christophermacgown/devcontainer-features
```

![image](https://user-images.githubusercontent.com/24955913/211874304-32dce42c-2d69-40a1-b122-7a508fa84856.png)

The OCI spec accepts a lower case, hence the artifacts are published to same. Can we update the case here?

2023-01-12 02:38 UTC, ChristopherMacGown commented
Thank you for the review, @samruddhikhandale I've made the changes you requested.

2023-01-12 17:04 UTC, samruddhikhandale approved these changes
⚡ ⚡

2023-01-12 17:04 UTC, merged