Add Balazs's features to collection
devcontainers/devcontainers.github.io pull request #138
Opened 2023-01-19 12:51 UTC by Balazs23

I've made two features (bezel, nx) what I was missing from the feature list

2023-01-19 17:53 UTC, samruddhikhandale requested changes
Nice, left one comment!

2023-01-19 17:53 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/balazs23/devcontainer-features
```suggestion
  ociReference: ghcr.io/balazs23/devcontainers-features
```
Can we update to match the `ociReference` here? Thanks! 

<img width="616" alt="image" src="https://user-images.githubusercontent.com/24955913/213522158-48387ccb-7131-44a7-aed4-6a26ac3ba2db.png">

2023-01-19 18:03 UTC, Balazs23 commented on _data/collection-index.yml
> +  ociReference: ghcr.io/balazs23/devcontainer-features
Fixed, thank you!

2023-01-23 17:15 UTC, samruddhikhandale requested changes
Looks like there is a merge conflict, can you help fix that? thanks!

2023-01-24 08:56 UTC, Balazs23 commented
> Looks like there is a merge conflict, can you help fix that? thanks!

Done :)

2023-01-24 18:10 UTC, samruddhikhandale approved these changes
Thank you! 🚀

2023-01-24 18:10 UTC, merged