Tailwindcss Standalone CLI
devcontainers/devcontainers.github.io pull request #148
Opened 2023-02-08 23:56 UTC by r3dpoint

Adding non-official Tailwindcss Standalone CLI devcontainer feature to the registry.

2023-02-09 19:56 UTC, samruddhikhandale requested changes
Awesome, thank you! 

Can you help resolve the merge conflicts?

2023-02-09 20:24 UTC, samruddhikhandale requested changes
left a minor comment

2023-02-09 20:24 UTC, samruddhikhandale commented on _data/collection-index.yml
> +
```suggestion

```

Nit: remove unwanted white spaces? thank you!

2023-02-09 21:02 UTC, samruddhikhandale approved these changes

2023-02-09 21:02 UTC, merged

2023-02-10 00:59 UTC, charlestonXsolutions reviewed
send it