Add condor devcontainer features
devcontainers/devcontainers.github.io pull request #157
Opened 2023-02-21 00:35 UTC by trestrantham

2023-02-21 17:36 UTC, samruddhikhandale requested changes
Thanks, left one comment!

2023-02-21 17:36 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  maintainer: @trestrantham
The yml parser does not allow `@` as the first character of the token, hence it results into build failures. Can you either remove `@` or double quote the value? Thanks!

2023-03-09 17:28 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  maintainer: @trestrantham
@trestrantham Pinging on this thread as a friendly reminder! :)

2023-03-09 18:10 UTC, trestrantham commented on _data/collection-index.yml
> +  maintainer: @trestrantham
@samruddhikhandale Thanks for the nudge! I actually ended up going a different direction with this (using local features) while I work out a different approach here. I will close this for now and open a new PR if/when it's ready for consumption. Cheers!

2023-03-09 18:10 UTC, closed without merging