add new feature 'watchman'
devcontainers/devcontainers.github.io pull request #159
Opened 2023-02-23 21:09 UTC by vvvrrooomm

used with e.g. sorbet

2023-02-23 21:35 UTC, samruddhikhandale requested changes
Left one comment, thanks!

2023-02-23 21:35 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/vvvrrooomm/watchman/watchman
```suggestion
  ociReference: ghcr.io/vvvrrooomm/watchman
```

This index adds an entry of the ociReference for collection metadata instead of individual Features. Thus, the author needs to only add a single entry irrespective of the number of Features that might exist in the repo. 

Can you update this? thanks!

2023-03-09 17:27 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/vvvrrooomm/watchman/watchman
Pinging on this thread as a friendly reminder! :)

2024-05-27 10:51 UTC, JustDontsnitchonme approved these changes

2024-05-27 10:53 UTC, JustDontsnitchonme approved these changes
>merge

2024-08-20 05:17 UTC, krishnprakash approved these changes

2024-09-02 11:04 UTC, FezVrasta commented
Any chance to see this merged? Right now it's really hard to get watchman working on devcontainers

2025-10-27 17:11 UTC, AlvaroRausell commented
Closing as stale

2025-10-27 17:11 UTC, closed without merging