Update dev container
devcontainers/devcontainers.github.io pull request #199
Opened 2023-04-21 23:37 UTC by bamurtaugh

- Update to the latest Jekyll dev container template
- Update readme with change
- Add .gitattributes to avoid line ending issues

2023-04-21 23:48 UTC, samruddhikhandale commented on .devcontainer/devcontainer.json
> +	"image": "mcr.microsoft.com/devcontainers/jekyll:0-bullseye",
```suggestion
	"image": "mcr.microsoft.com/devcontainers/jekyll:1-bullseye",
```

Yesterday, we did a release which bumps the major version of this image.
Opened https://github.com/devcontainers/templates/pull/149 just now to sync with those changes.

Ref: https://github.com/devcontainers/images/pull/516 uses ruby 3.2 instead of ruby 2.7 which could be a breaking change for folks.
As this is a major version change, can we ensure that this dev config works well with the website?

2023-04-24 16:52 UTC, bamurtaugh commented on .devcontainer/devcontainer.json
> +	"image": "mcr.microsoft.com/devcontainers/jekyll:0-bullseye",
I bumped the version and it works with ruby 3.2! Thanks for pointing this out.

2023-04-24 17:13 UTC, samruddhikhandale commented on .devcontainer/devcontainer.json
> +	"image": "mcr.microsoft.com/devcontainers/jekyll:0-bullseye",
Sweet, thanks!

2023-04-24 17:18 UTC, samruddhikhandale requested changes
Thank you for updating the dev config, left few other comments.

2023-04-24 17:18 UTC, samruddhikhandale commented on .devcontainer/post-create.sh
> -#!/bin/sh
Looks like this file will still be needed for installing bundler and gems?

2023-04-24 17:18 UTC, samruddhikhandale commented on .devcontainer/devcontainer.json
> -	"postCreateCommand": "sh .devcontainer/post-create.sh",
Same here. We'd probably need this command as well?

2023-04-24 17:24 UTC, bamurtaugh commented on .devcontainer/post-create.sh
> -#!/bin/sh
Thanks for pointing this out. I had directly included this file previously as it was required in the vscode-dev-containers Jekyll definition: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/jekyll/.devcontainer/post-create.sh.

But with our move to the devcontainers org, I thought this would be automatically referenced when I updated the devcontainer.json to point at our new prebuilt Jekyll image. For instance, I see the postCreateCommand and post-create.sh correctly configured in https://github.com/devcontainers/images/blob/main/src/jekyll/.devcontainer/devcontainer.json#L24.

I didn't think I'd need to re-reference it explicitly here if I'm using our prebuilt image, but maybe I'm forgetting?

2023-04-24 17:24 UTC, bamurtaugh commented on .devcontainer/devcontainer.json
> -	"postCreateCommand": "sh .devcontainer/post-create.sh",
Same as my thinking above, I thought using the prebuild image that includes this would be sufficient https://github.com/devcontainers/images/blob/main/src/jekyll/.devcontainer/devcontainer.json#L24.

2023-04-24 17:56 UTC, samruddhikhandale commented on .devcontainer/post-create.sh
> -#!/bin/sh
That makes sense, thank you for the explanation. I somehow missed that 😅

2023-04-24 17:57 UTC, samruddhikhandale approved these changes
Appreciate it 👏

2023-04-24 17:57 UTC, merged