fix broken link
devcontainers/devcontainers.github.io pull request #209
Opened 2023-05-16 15:11 UTC by joshspicer

2023-05-16 15:13 UTC, jkeech requested changes, later dismissed

2023-05-16 15:13 UTC, jkeech commented on _implementors/features-distribution.md
> +* The project must have a `.devcontainer/` folder at the root of the [**project workspace folder**](/spec/#project-workspace-folder).
What is the final link you are trying to create? https://containers.dev/spec/#project-workspace-folder doesn't work for me.

2023-05-24 18:00 UTC, samruddhikhandale requested changes

2023-05-24 18:00 UTC, samruddhikhandale commented on _implementors/features-distribution.md
> +* The project must have a `.devcontainer/` folder at the root of the [**project workspace folder**](/implementors/spec/#project-workspace-folder).
```suggestion
* The project must have a `.devcontainer/` folder at the root of the [**project workspace folder**](/_implementors/spec.md#project-workspace-folder).
```

This link doesn't work for me, probably we need to change to ☝️ ?

2023-05-25 02:07 UTC, joshspicer commented on _implementors/features-distribution.md
> +* The project must have a `.devcontainer/` folder at the root of the [**project workspace folder**](/implementors/spec/#project-workspace-folder).
This is where i'm trying to link to :D 
https://containers.dev/implementors/spec/#project-workspace-folder

2023-05-25 15:51 UTC, samruddhikhandale commented on _implementors/features-distribution.md
> +* The project must have a `.devcontainer/` folder at the root of the [**project workspace folder**](/implementors/spec/#project-workspace-folder).
Huh 🤦‍♀️

2023-05-25 15:51 UTC, samruddhikhandale approved these changes

2023-05-25 15:51 UTC, samruddhikhandale approved these changes

2023-07-11 22:29 UTC, merged