Update collection-index.yml
devcontainers/devcontainers.github.io pull request #218
Opened 2023-05-29 06:57 UTC by NikitaKurpas

This PR adds all features in NikitaKurpas/features repo. There's currently only 1 feature: [vapor toolbox](https://github.com/vapor/toolbox).

2023-05-30 15:45 UTC, samruddhikhandale requested changes

2023-05-30 15:45 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/NikitaKurpas/features
```suggestion
  ociReference: ghcr.io/nikitakurpas/features
```

Hi 👋

The ORAS spec requires the `ociReference` to be in lower case. Can we update here, thanks?
The supporting tools do help convert the case, however, its better to sync as much as possible.

2023-05-31 09:12 UTC, NikitaKurpas commented on _data/collection-index.yml
> +  ociReference: ghcr.io/NikitaKurpas/features
Hey, thanks for the suggestion 👍🏻 Applied.

2023-05-31 15:45 UTC, samruddhikhandale approved these changes
Looks good, thanks!

2023-05-31 15:45 UTC, merged