Update collection-index.yml with NEAR Features
devcontainers/devcontainers.github.io pull request #347
Opened 2024-02-04 13:37 UTC by njelich

2024-02-05 17:21 UTC, samruddhikhandale requested changes
Left a comment!

2024-02-05 17:21 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/near/features
```suggestion
  ociReference: ghcr.io/near/near-devcontainers
```

Hi 👋 

Looks like there is something wrong with the artifact, see 👇 Also, I can not see any Feature code in https://github.com/near/near-devcontainers which is the cause of an empty artifact. @njelich Can you help fix it? Thanks! 

![image](https://github.com/devcontainers/devcontainers.github.io/assets/24955913/ddcbc280-9492-48ce-8b92-6e865c991171)

2024-02-06 10:44 UTC, njelich commented on _data/collection-index.yml
> +  ociReference: ghcr.io/near/features
The features are defined in https://github.com/near/near-devcontainers/tree/main/.devcontainer

2024-02-06 17:40 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/near/features
From https://github.com/near/near-devcontainers/tree/main/.devcontainer, I can see that you want to publish `cargo-near` and `near-cli` Features. However, I don't see the corresponding artifacts in https://github.com/orgs/near/packages?repo_name=near-devcontainers

From https://github.com/near/near-devcontainers/blob/main/.github/workflows/publish-features.yml#L16, the action you are using to publish Features doesn't look right to me.

<img width="1389" alt="image" src="https://github.com/devcontainers/devcontainers.github.io/assets/24955913/93e885b5-b9a7-436b-9c7a-469e0de71512">


Have you taken a look at https://github.com/devcontainers/feature-starter and https://containers.dev/implementors/features-distribution/ ?

2024-02-07 19:54 UTC, samruddhikhandale requested changes

2024-02-07 19:54 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/near/near-devcontainers
It still seems off, see 👇 

![image](https://github.com/devcontainers/devcontainers.github.io/assets/24955913/154508ee-967b-4317-a426-120768555bd0)

I wonder if it's due to repository name and artifact name not being in sync. Also, we don't support and maintain `devcontainers-community/publish-feature@v1`, hence unfortunately, I won't be able to provide much guidance

2025-08-19 06:44 UTC, closed without merging