contributing my feature wrappers for https://github.com/nvbn/thefuck
devcontainers/devcontainers.github.io pull request #349
Opened 2024-02-05 15:10 UTC by GeorgOfenbeck

Heavily inspired by @danielbraun89 implementations

2024-02-05 17:42 UTC, samruddhikhandale requested changes
Left one minor comment!

2024-02-05 17:42 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/GeorgOfenbeck/features
```suggestion
  ociReference: ghcr.io/georgofenbeck/features
```

Hi 👋

The ORAS spec requires the `ociReference` to be in lower case. Can we update here, thanks?
The supporting tools do help convert the case, however, its better to sync as much as possible.

2024-02-06 08:22 UTC, GeorgOfenbeck commented on _data/collection-index.yml
> +  ociReference: ghcr.io/GeorgOfenbeck/features
of course! thanks

2024-02-06 17:34 UTC, samruddhikhandale approved these changes, later dismissed
Looks good, thanks!

2024-02-06 17:35 UTC, samruddhikhandale approved these changes

2024-02-06 17:35 UTC, merged