Add issue template & automation for community contributions
devcontainers/devcontainers.github.io pull request #354
Opened 2024-02-17 00:16 UTC by bamurtaugh

Fixes https://github.com/devcontainers/devcontainers.github.io/issues/244

As part of https://github.com/devcontainers/spec/issues/405, @samruddhikhandale had the excellent suggestion to incorporate https://github.com/devcontainers/devcontainers.github.io/issues/244, which involves both issue templates + automation for adding content from issues into code.

In this case, I've added:
- An issue template `update-collection.yml` to help contributors more easily provide the info we require as part of community contributions
- A GitHub Actions workflow for checking for a comment `#sign-off` from a [spec maintainer](https://github.com/orgs/devcontainers/teams/maintainers)
- Once a maintainer signs off, the issue is parsed, and its collection is added to `collection-index.yml`
- The issue is then closed, thanking the user for their contribution and linking them to the community index to check out the update!

You can try this out in [my fork](https://github.com/bamurtaugh/devcontainers.github.io):
- Create an issue with the new template (quick access link [here](https://github.com/bamurtaugh/devcontainers.github.io/issues/new?template=update-collection.yml))
- Comment `#sign-off` (this needs to be done by a member of the [maintainers GH team](https://github.com/orgs/devcontainers/teams/maintainers))
- Observe as the issue is soon closed and the index is updated!

[Here's an example issue](https://github.com/bamurtaugh/devcontainers.github.io/issues/42) where I completed this flow. The code change performed by the GitHub Action is [here](https://github.com/bamurtaugh/devcontainers.github.io/commit/81e9c47884545f679fae17eae2e34e4a5fb5c1ce).

@samruddhikhandale I'd love to get your review on this - does the flow work well for you? Any edge cases I might not have accounted for? Does the wording throughout (in the template, in the comment automatically added after, etc) make sense?

2024-02-21 20:27 UTC, samruddhikhandale commented
@bamurtaugh I tried testing on your [fork](https://github.com/bamurtaugh/devcontainers.github.io-fork), and created two issues. However, it did not create a PR for me 😕 
Looks like https://github.com/bamurtaugh/devcontainers.github.io-fork/actions/workflows/collection.yml wasn't triggered.

2024-02-21 20:32 UTC, bamurtaugh commented
So strange it skipped the job run! I just tried adding your username explicitly to the collection.yml to see if that'd help: https://github.com/bamurtaugh/devcontainers.github.io-fork/blob/gh-pages/.github/workflows/collection.yml.

2024-02-21 20:33 UTC, bamurtaugh commented
> Looks like https://github.com/bamurtaugh/devcontainers.github.io-fork/blob/gh-pages/.github/workflows/collection.yml#L10 needs to be tweaked in your fork.

Yeah, I agree. Could you see if commenting `#sign-off` works now, since I added your username explicitly? Wondering if the check for being part of the maintainers team doesn't work well.

2024-02-21 21:29 UTC, samruddhikhandale requested changes
This is super cool and will be super helpful for the community! 
Thank you so much for contributing this 👏

2024-02-21 21:29 UTC, samruddhikhandale commented on _data/update-collection.js
> +`\n- name: ${name}
Looks like we are adding empty lines in between two entries? This might cause some issues with the crawler, can we remove them? 

See https://github.com/bamurtaugh/devcontainers.github.io-fork/commit/75a3477fcfb50dc829cd88343d11c64929b29815#diff-213a25c23998b235e92e81da59bbf14a591fa6332ee3d14a662ad4471e621bcbR697

2024-02-21 21:29 UTC, samruddhikhandale commented on .github/workflows/collection.yml
> +    runs-on: ubuntu-latest
We now need to explicitly specify the permissions we give to a workflow. Can you add the following?

```
permissions:
     contents: write
     issues: write
    pull-request: write
```

2024-02-21 21:29 UTC, samruddhikhandale commented on .github/workflows/collection.yml
> +    runs-on: ubuntu-latest
Feel free to check https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview and add other permissions if necessary.

2024-02-21 21:29 UTC, samruddhikhandale commented on .github/workflows/collection.yml
> +    if: contains(github.event.comment.body, '#sign-off') && (github.event.comment.user.login == 'bamurtaugh' || contains(github.event.comment.user.login, 'devcontainers/maintainers'))
```suggestion
    if: contains(github.event.comment.body, '#sign-off') && contains(github.event.comment.user.login, 'devcontainers/maintainers'))
```

Should we add you to devcontainers/maintainers instead?

2024-02-21 21:29 UTC, samruddhikhandale commented on .github/workflows/collection.yml
> +    if: contains(github.event.comment.body, '#sign-off') && (github.event.comment.user.login == 'bamurtaugh' || contains(github.event.comment.user.login, 'devcontainers/maintainers'))
According to copilot, `contains(github.event.comment.user.login, 'devcontainers/maintainers'))` might not work. See 👇 

No, the syntax you've provided is incorrect for a GitHub Actions workflow.

If you want to check if the user who commented is a member of the 'devcontainers/maintainers' team, you can't do it directly in the workflow file. GitHub Actions does not provide a direct way to check team membership.

However, you can create a script that uses the GitHub API to check if a user is a member of a specific team, and then call that script from your workflow.

Here is a simple example of how you might do this using a bash script and the GitHub CLI:
```
#!/bin/bash
user="$1"
team="devcontainers/maintainers"

if gh team view "$team" --json members | jq -e --arg user "$user" '.members[] | select(.login == $user)'; then
  echo "$user is a member of $team"
  exit 0
else
  echo "$user is not a member of $team"
  exit 1
fi
```

You can call this script from your workflow like this:

```
- name: Check if user is a team member
  run: ./check_team_membership.sh ${{ github.event.comment.user.login }}
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

2024-02-21 21:29 UTC, samruddhikhandale commented on .github/workflows/collection.yml
> +          node-version: '16'
```suggestion
          node-version: '20'
```

As 16 has reached EOL

2024-02-21 21:29 UTC, samruddhikhandale commented on .github/workflows/collection.yml
> +          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
This might not work due to our org polcies. Can you add something similar to https://github.com/devcontainers/images/blob/main/.github/workflows/version-history.yml#L89-L121 instead?

2024-02-21 21:29 UTC, samruddhikhandale commented on .github/workflows/collection.yml
> +          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
I'll ensure PAT is available to this repo!

2024-02-21 21:29 UTC, samruddhikhandale commented on .github/workflows/collection.yml
> +          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
💡 Instead of "Github-actions", how about we use credentials of https://github.com/devcontainers-bot ?

2024-02-21 21:29 UTC, samruddhikhandale commented on _data/update-collection.js
> +        case '### collection name':
If someone edits the issue and accidentally manipulates it, then this action would fail 🤔 
As a maintainer, could be hard to remember this. Maybe add a note to the issue template?

2024-02-21 21:29 UTC, samruddhikhandale commented on .github/workflows/collection.yml
> +    if: contains(github.event.comment.body, '#sign-off') && (github.event.comment.user.login == 'bamurtaugh' || contains(github.event.comment.user.login, 'devcontainers/maintainers'))
Committing directly to a repo is not allowed, every commit needs a corresponding PR. Even though we use BOT's PAT, it won't have those privileges.

@bamurtaugh How about we remove the `#sign-off` bit, and once someone opens a new issue with the new Template, we open a PR?

2024-02-26 19:03 UTC, bamurtaugh commented on _data/update-collection.js
> +`\n- name: ${name}
I might be missing something obvious, but not including `\n` then doesn't put the entry on a new line, but `\n` incorrectly adds a whole blank line 🤔 will try to keep experimenting here.

2024-02-26 19:12 UTC, bamurtaugh commented on .github/workflows/collection.yml
> +    if: contains(github.event.comment.body, '#sign-off') && (github.event.comment.user.login == 'bamurtaugh' || contains(github.event.comment.user.login, 'devcontainers/maintainers'))
If we can get this check to work, then yes! It seems the check isn't working (as we saw that I needed to add your username explicitly)

2024-02-26 19:20 UTC, bamurtaugh commented on .github/workflows/collection.yml
> +    if: contains(github.event.comment.body, '#sign-off') && (github.event.comment.user.login == 'bamurtaugh' || contains(github.event.comment.user.login, 'devcontainers/maintainers'))
Resolving since I've added myself (at least temporarily) to the team

2024-02-26 19:20 UTC, bamurtaugh commented on .github/workflows/collection.yml
> +    runs-on: ubuntu-latest
Added!

2024-02-26 21:48 UTC, bamurtaugh commented on _data/update-collection.js
> +`\n- name: ${name}
Found a solution!

2024-02-27 00:39 UTC, bamurtaugh commented on .github/workflows/collection.yml
> +    if: contains(github.event.comment.body, '#sign-off') && (github.event.comment.user.login == 'bamurtaugh' || contains(github.event.comment.user.login, 'devcontainers/maintainers'))
As an update: I'm actively trying to switch this over to a PR workflow in my fork (you can see progress [here](https://github.com/bamurtaugh/devcontainers.github.io-fork/blob/gh-pages/.github/workflows/collection.yml)). Since I'm not deeply experienced with creating GH Actions, I'm trying to get a lot of help from Copilot 😄 so I'm not sure how close I am or not to getting this working (been running into a whole bunch of different errors).

2024-04-05 22:21 UTC, bamurtaugh commented
Closing in favor of https://github.com/devcontainers/devcontainers.github.io/pull/382!

2024-04-05 22:21 UTC, closed without merging