Updated the file with latest spec file.
devcontainers/devcontainers.github.io pull request #361
Opened 2024-02-26 20:55 UTC by bhupendra-vaishnav

Updated the file with latest spec file to fix the issue # [352](https://github.com/devcontainers/devcontainers.github.io/issues/352)

2024-02-26 22:26 UTC, samruddhikhandale requested changes

2024-02-26 22:26 UTC, samruddhikhandale commented on _implementors/json_reference.md
> +| `name` | string | A name for the dev container displayed in the UI |
revert?

2024-02-26 22:26 UTC, samruddhikhandale commented on _implementors/json_reference.md
> +| `appPort` | integer,<br>string,<br>array |  In most cases, we recommend using the new [forwardPorts property](#general-devcontainerjson-properties). This property accepts a port or array of ports t
Why do we need to update to `#general-devcontainerjson-properties` ? I don't see that section present

2024-02-26 22:26 UTC, samruddhikhandale commented on _implementors/json_reference.md
> -| `initializeCommand` | string,<br>array,<br>object | A command string or list of command arguments to run on the **host machine** before the container is created.<br /><br /> ⚠️ The command is run w
Let's keep this extra `<br>`. It's good for visibility.

2024-02-26 22:26 UTC, samruddhikhandale commented on _implementors/json_reference.md
> +For each command property, if the value is a single string, it will be run in `/bin/sh`. Use `&&` in a string to execute multiple commands. For example, `"yarn install"` or `"apt-get update && apt-ge
Revert?

2024-02-27 01:16 UTC, bhupendra-vaishnav commented on _implementors/json_reference.md
> +| `name` | string | A name for the dev container displayed in the UI |
revereted.

2024-02-27 01:16 UTC, bhupendra-vaishnav commented on _implementors/json_reference.md
> +| `appPort` | integer,<br>string,<br>array |  In most cases, we recommend using the new [forwardPorts property](#general-devcontainerjson-properties). This property accepts a port or array of ports t
done

2024-02-27 01:16 UTC, bhupendra-vaishnav commented on _implementors/json_reference.md
> -| `initializeCommand` | string,<br>array,<br>object | A command string or list of command arguments to run on the **host machine** before the container is created.<br /><br /> ⚠️ The command is run w
Do you want to add `<br><br>` or `<br/><br/>` ?

2024-02-27 01:16 UTC, bhupendra-vaishnav commented on _implementors/json_reference.md
> +| `service` | string | **Required** when [using Docker Compose](https://docs.docker.com/compose/). The name of the service `devcontainer.json` supporting services / tools should connect to once runni
I am seeing some changes here for this link `[using Docker Compose]`. What should I do? Revert?

2024-02-27 01:16 UTC, bhupendra-vaishnav commented on _implementors/json_reference.md
> +| `postStartCommand` 🏷️ | string,<br>array,<br>object | A command to run each time the container is successfully started.<br>Note that the array syntax will execute the command without a shell. You c
I am seeing similar change for single-line-break HTML tag here. What should we do ? All revert to two single-line-break tag?

Also look at next line.

2024-02-27 18:12 UTC, samruddhikhandale commented on _implementors/json_reference.md
> +| `service` | string | **Required** when [using Docker Compose](https://docs.docker.com/compose/). The name of the service `devcontainer.json` supporting services / tools should connect to once runni
This looks good!

2024-02-27 18:12 UTC, samruddhikhandale commented on _implementors/json_reference.md
> -| `initializeCommand` | string,<br>array,<br>object | A command string or list of command arguments to run on the **host machine** before the container is created.<br /><br /> ⚠️ The command is run w
Let's keep the old changes intact (which were `<br><br>`)

2024-02-27 18:12 UTC, samruddhikhandale commented on _implementors/json_reference.md
> +| `postStartCommand` 🏷️ | string,<br>array,<br>object | A command to run each time the container is successfully started.<br>Note that the array syntax will execute the command without a shell. You c
Let's keep it as it is

2024-02-27 18:12 UTC, samruddhikhandale commented on _implementors/json_reference.md
> +| `${devcontainerId}` | Any | Allow features to refer to an identifier that is unique to the dev container they are installed into and that is stable across rebuilds.<br> The properties supporting it
```suggestion
| `${devcontainerId}` | Any | Allow Features to refer to an identifier that is unique to the dev container they are installed into and that is stable across rebuilds.<br> The properties supporting it in devcontainer.json are: `name`, `runArgs`, `initializeCommand`, `onCreateCommand`, `updateContentCommand`, `postCreateCommand`, `postStartCommand`, `postAttachCommand`, `workspaceFolder`, `workspaceMount`, `mounts`, `containerEnv`, `remoteEnv`, `containerUser`, `remoteUser`, and `customizations`. |

```

I know you copied over this, but features should be with uppercase `F`

2024-02-28 01:35 UTC, bhupendra-vaishnav commented on _implementors/json_reference.md
> -| `initializeCommand` | string,<br>array,<br>object | A command string or list of command arguments to run on the **host machine** before the container is created.<br /><br /> ⚠️ The command is run w
done

2024-02-28 18:48 UTC, samruddhikhandale requested changes

2024-02-28 18:48 UTC, samruddhikhandale commented on _implementors/json_reference.md
> -| `initializeCommand` | string,<br>array,<br>object | A command string or list of command arguments to run on the **host machine** before the container is created.<br /><br /> ⚠️ The command is run w
@bhupendra-vaishnav Did you miss to push the changes? I still see old diff with missing `<br>`

2024-02-29 01:06 UTC, bhupendra-vaishnav commented on _implementors/json_reference.md
> +For each command property, if the value is a single string, it will be run in `/bin/sh`. Use `&&` in a string to execute multiple commands. For example, `"yarn install"` or `"apt-get update && apt-ge
done

2024-02-29 01:07 UTC, bhupendra-vaishnav commented on _implementors/json_reference.md
> -| `initializeCommand` | string,<br>array,<br>object | A command string or list of command arguments to run on the **host machine** before the container is created.<br /><br /> ⚠️ The command is run w
fixed and I re-validated. I think it should be good now.

2024-02-29 01:12 UTC, bhupendra-vaishnav commented
Would this be visible on the page? Look at blue-highlighted section in attached screen-shot : 
<img width="1316" alt="image" src="https://github.com/devcontainers/devcontainers.github.io/assets/148317470/37b29cf8-640d-409f-9cc9-742bb42b6a24">

2024-03-01 01:02 UTC, samruddhikhandale approved these changes

2024-03-01 01:03 UTC, merged