Update collection-index.yml
devcontainers/devcontainers.github.io pull request #362
Opened 2024-03-03 09:56 UTC by dlouwers

Added bob build system

2024-03-04 17:32 UTC, samruddhikhandale requested changes
Thanks for the new additions, left few comments.

2024-03-04 17:32 UTC, samruddhikhandale commented on _data/collection-index.yml
> +- name: Bob Build System
Can you add this new entry to the bottom of this file? Thanks!

2024-03-04 17:32 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/dlouwers/devcontainer-feature-bob/bob
Hi 👋

Can you help change the visibility of this "metadata" package to public? The [index](https://containers.dev/features) won't be able to crawl the Features in `dlouwers/devcontainer-feature-bob` if it's private.

Feel free to look at https://containers.dev/guide/author-a-feature#publishing for information.

2024-03-04 17:32 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/dlouwers/devcontainer-feature-bob/bob
```suggestion
  ociReference: ghcr.io/dlouwers/devcontainer-feature-bob
```

The `ociReference` here refers to the collection metadata artifact instead of the individual Features. Hence, the author needs to only add a single entry irrespective of the number of Features that might exist in their repository.

Can you help update this? thanks!

2024-03-05 10:10 UTC, dlouwers commented on _data/collection-index.yml
> +- name: Bob Build System
Have moved it to the bottom

2024-03-05 10:11 UTC, dlouwers commented on _data/collection-index.yml
> +  ociReference: ghcr.io/dlouwers/devcontainer-feature-bob/bob
Updated the reference to point to the root of the features and updated the title to reflect this

2024-03-05 10:11 UTC, dlouwers commented on _data/collection-index.yml
> +  ociReference: ghcr.io/dlouwers/devcontainer-feature-bob/bob
Visibility should be public now

2024-03-05 16:39 UTC, samruddhikhandale approved these changes
Looks good, thanks!

2024-03-05 16:39 UTC, merged