Add OpenCodeCo
devcontainers/devcontainers.github.io pull request #372
Opened 2024-03-22 23:31 UTC by leocavalcante

2024-03-22 23:50 UTC, samruddhikhandale requested changes

2024-03-22 23:50 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/opencodeco/devcontainers
Hi 👋

Can you help change the visibility of this "metadata" package  to public? The [index](https://containers.dev/features) won't be able to crawl the Features in `opencodeco/devcontainers` if it's private.

Feel free to look at https://containers.dev/guide/author-a-feature#publishing for information.

2024-03-23 00:09 UTC, leocavalcante commented on _data/collection-index.yml
> +  ociReference: ghcr.io/opencodeco/devcontainers
Here is it :) https://github.com/opencodeco/devcontainers/pkgs/container/devcontainers

2024-03-23 00:12 UTC, samruddhikhandale approved these changes
Awesome, thank you! 🎉

2024-03-23 00:12 UTC, merged