Update collection-index.yml
devcontainers/devcontainers.github.io pull request #374
Opened 2024-03-27 00:36 UTC by prulloac

Added templates repository to the public list and updated my name as maintainer

2024-03-27 15:50 UTC, samruddhikhandale requested changes

2024-03-27 15:50 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/prulloac/devcontainer-templates
Hi 👋

Can you help change the visibility of this "metadata" package (and your Template packages) to public? The [index](https://containers.dev/templates) won't be able to crawl the Templates in `prulloac/devcontainer-templates` if it's private.

2024-03-28 00:08 UTC, prulloac commented on _data/collection-index.yml
> +  ociReference: ghcr.io/prulloac/devcontainer-templates
Hi @samruddhikhandale , thanks for the tip. visibility is now public!

2024-03-28 16:20 UTC, samruddhikhandale approved these changes
Looks great, thank you!

2024-03-28 16:20 UTC, merged