rename Jetpack.io to Jetify.io
devcontainers/devcontainers.github.io pull request #395
Opened 2024-04-25 10:32 UTC by alexravenna

## What type of PR is this?

- [ ] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [x] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

2024-04-26 00:03 UTC, samruddhikhandale requested changes
Thanks for the spec update ⚡ 

Left one comment, thanks!

2024-04-26 00:03 UTC, samruddhikhandale commented on supporting.md
> +[Jetify.io](https://jetify.io) (formerly jetpack.io) is a [Nix](https://nixos.org/)-based service for deploying applications. [DevBox](https://www.jetify.io/devbox/) provides a way to use Nix to gene
```suggestion
[Jetify.io](https://jetify.io) (formerly jetpack.io) is a [Nix](https://nixos.org/)-based service for deploying applications. [DevBox](https://www.jetify.com/devbox/) provides a way to use Nix to generate a development environment. [Jetify.io's VS Code extension](https://marketplace.visualstudio.com/items?itemName=jetpack-io.devbox) allows you to quickly take advantage of DevBox in any Dev Container Spec supporting tool or service. 

```

https://www.jetify.io/devbox/ doesn't open for me 🤔

2024-04-26 04:30 UTC, alexravenna commented on supporting.md
> +[Jetify.io](https://jetify.io) (formerly jetpack.io) is a [Nix](https://nixos.org/)-based service for deploying applications. [DevBox](https://www.jetify.io/devbox/) provides a way to use Nix to gene
Thanks for the catch! 😊 My bad...they're called just "Jetify", not "Jetify.io". I corrected the text accordingly 🙂.

2024-04-29 22:12 UTC, samruddhikhandale approved these changes
Thanks! ✨

2024-04-29 22:13 UTC, merged