Add Veryl features
devcontainers/devcontainers.github.io pull request #396
Opened 2024-04-26 03:42 UTC by dalance

## What type of PR is this?

- [x] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Description

This PR adds Veryl features.

### Collection checklist
_If your PR contributes a new collection, please utilize this checklist:_
- [x] Collection name
- [x] Maintainer name
- [x] Maintainer contact link (i.e. link to a GitHub repo, email)
- [x] Repository URL
- [x] OCI Reference
- [x] I acknowledge that this collection provides new functionality, distinct from the existing collections part of this index.

2024-04-26 16:14 UTC, samruddhikhandale requested changes

2024-04-26 16:14 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/veryl-lang/devcontainer-features
Hi 👋

Can you help change the visibility of this "metadata" package to public? The [index](https://containers.dev/features) won't be able to crawl the Features in `veryl-lang/devcontainer-features` if it's private.

Feel free to look at https://containers.dev/guide/author-a-feature#publishing for information.

2024-04-26 23:16 UTC, dalance commented on _data/collection-index.yml
> +  ociReference: ghcr.io/veryl-lang/devcontainer-features
Thank you for your support.
I changed it to public.

2024-04-29 15:56 UTC, samruddhikhandale approved these changes
Looks good, thank you ✨

2024-04-29 15:56 UTC, merged