Add skriptfabrik feature collection
devcontainers/devcontainers.github.io pull request #400
Opened 2024-05-13 13:02 UTC by schroedan

## What type of PR is this?

- [x] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Description

This PR is about to add the skriptfabrik dev container features to the list.

### Collection checklist
_If your PR contributes a new collection, please utilize this checklist:_
- [x] Collection name: Dev Container Features by skriptfabrik
- [x] Maintainer name: skriptfabrik
- [x] Maintainer contact link (i.e. link to a GitHub repo, email): https://github.com/skriptfabrik/
- [x] Repository URL: https://github.com/skriptfabrik/devcontainer-features/
- [x] OCI Reference: ghcr.io/skriptfabrik/devcontainer-features
- [x] I acknowledge that this collection provides new functionality, distinct from the existing collections part of this index.

2024-05-13 18:23 UTC, samruddhikhandale requested changes
Thank you for the addition, left one comment.

2024-05-13 18:23 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/skriptfabrik/devcontainer-features
Hi 👋

Can you help change the visibility of this "metadata" package (and your Feature package) to public? The [index](https://containers.dev/features) won't be able to crawl the Features in `skriptfabrik/devcontainer-features` if it's private.

Feel free to look at https://containers.dev/guide/author-a-feature#publishing for information.

2024-05-14 08:49 UTC, schroedan commented on _data/collection-index.yml
> +  ociReference: ghcr.io/skriptfabrik/devcontainer-features
Hello, I have set the package `skriptfabrik/devcontainer-features` to public. Sorry for the inconvenience.

2024-05-14 15:59 UTC, samruddhikhandale approved these changes
Thank you 🎉

2024-05-14 15:59 UTC, merged