Add OpenFGA CLI feature
devcontainers/devcontainers.github.io pull request #405
Opened 2024-05-24 03:15 UTC by partydrone

## What type of PR is this?

- [x] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Related Issues

- Related Issue #
- Closes #

## Description

This pull request introduces a new devcontainer feature for installing the OpenFGA CLI. The feature supports both `amd64` and `arm64` Linux architectures and is compatible with the following package types:

- APK
- DEB
- RPM

### Collection checklist
_If your PR contributes a new collection, please utilize this checklist:_
- [ ] Collection name
- [ ] Maintainer name
- [ ] Maintainer contact link (i.e. link to a GitHub repo, email)
- [ ] Repository URL
- [ ] OCI Reference
- [ ] I acknowledge that this collection provides new functionality, distinct from the existing collections part of this index.

2024-05-25 00:01 UTC, samruddhikhandale requested changes

2024-05-25 00:01 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  maintenance: Andrew Porter
```suggestion
  maintainer: Andrew Porter
```

2024-05-25 00:01 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/partydrone/devcontainer/features/openfga-cli
```suggestion
  ociReference: ghcr.io/partydrone/devcontainer/features
```

Hi 👋 

The `ociReference` here refers to the collection metadata artifact instead of the individual Features. Hence, the author needs to only add a single entry irrespective of the number of Features that might exist in their repository.

Can you help update this? thanks!

2024-05-25 03:25 UTC, partydrone commented on _data/collection-index.yml
> +  ociReference: ghcr.io/partydrone/devcontainer/features/openfga-cli
No problem! Thank you for clarifying. 🙂

2024-05-28 18:43 UTC, samruddhikhandale approved these changes
Looks good, thanks!

2024-05-28 18:43 UTC, merged