Add weslyg devcontainer feature repository
devcontainers/devcontainers.github.io pull request #408
Opened 2024-05-26 20:59 UTC by WeslyG

## What type of PR is this?

- [ ] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Related Issues

- Related Issue #
- Closes #

## Description

_Please replace this line with a description of your PR._

### Collection checklist
_If your PR contributes a new collection, please utilize this checklist:_
- [ ] Collection name
- [ ] Maintainer name
- [ ] Maintainer contact link (i.e. link to a GitHub repo, email)
- [ ] Repository URL
- [ ] OCI Reference
- [ ] I acknowledge that this collection provides new functionality, distinct from the existing collections part of this index.

2024-05-28 22:50 UTC, samruddhikhandale requested changes, later dismissed

2024-05-28 22:50 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/weslyg/features
Hi 👋

Can you help change the visibility of your Feature packages to public? Looks like it's private, see https://github.com/WeslyG?tab=packages&repo_name=features as I'd expect hashicorp-mirror package to exist.

Feel free to look at https://containers.dev/guide/author-a-feature#publishing for information.

2025-10-27 17:15 UTC, AlvaroRausell approved these changes

2025-10-27 17:16 UTC, AlvaroRausell approved these changes

2026-01-05 09:55 UTC, merged