Updated collection-index.yml
devcontainers/devcontainers.github.io pull request #421
Opened 2024-06-12 20:09 UTC by ChaosWars

Added Synology features

## What type of PR is this?

- [ x] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Description

Added Synology features. Currently, the only feature `synology-toolkit` facilitates development for Synology NAS devices utilizing the [Synology toolkit](https://help.synology.com/developer-guide/toolkit/toolkit.html)

2024-06-14 00:15 UTC, samruddhikhandale requested changes

2024-06-14 00:15 UTC, samruddhikhandale commented on _data/collection-index.yml
> +- name: Synology devcontainer templates
```suggestion
- name: Synology devcontainer Templates
```

Matching with Dev Containers terminology.

2024-06-14 00:15 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/ChaosWars/synology-features
```suggestion
  ociReference: ghcr.io/chaoswars/synology-features
```

Hi 👋

The ORAS spec requires the `ociReference` to be in lower case. Can we update here, thanks?

The supporting tools do help convert the case, however, its better to sync as much as possible.

2024-06-14 00:15 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/ChaosWars/synology-features
Can you help change the visibility of this metadata package to public? The [index](https://containers.dev/templates) won't be able to crawl for the Templates in `chaoswars/synology-features` if it's private.

2024-06-14 11:14 UTC, ChaosWars commented on _data/collection-index.yml
> +  ociReference: ghcr.io/ChaosWars/synology-features
It should already be set to public, I just rechecked and it seems to be set correctly with visibility to public.

2024-06-14 15:49 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/ChaosWars/synology-features
![image](https://github.com/user-attachments/assets/18541be2-7285-4720-abff-e58267ec52f8)

The toolkit package is correctly set to public, however, the metadata package doesn't seem to exist (it should have the name `synology-features`

2024-06-16 12:19 UTC, ChaosWars commented on _data/collection-index.yml
> +  ociReference: ghcr.io/ChaosWars/synology-features
My bad, `synology-toolkit/toolkiit`  was set to public, but `synology-features` was still set to private. It should be resolved now

2024-06-17 16:12 UTC, samruddhikhandale approved these changes
Thanks!

2024-06-17 16:12 UTC, merged