Update collection-index.yml
devcontainers/devcontainers.github.io pull request #441
Opened 2024-07-27 09:22 UTC by gvatsal60

## What type of PR is this?

- [X] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Description

Added new devcontainer collection 
pre-commit(via pip) and sonarlint

### Collection checklist
_If your PR contributes a new collection, please utilize this checklist:_
- [X] Collection name
- [X] Maintainer name
- [X] Maintainer contact link (i.e. link to a GitHub repo, email)
- [X] Repository URL
- [X] OCI Reference
- [X] I acknowledge that this collection provides new functionality, distinct from the existing collections part of this index.

2024-07-29 17:02 UTC, samruddhikhandale requested changes

2024-07-29 17:02 UTC, samruddhikhandale commented on _data/collection-index.yml
> +- name: pre-commit(via pip)
As both the Features are published from the same repo, we don't need two entries.

Can you remove one of them and probably update the name accordingly?

2024-07-29 17:02 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/gvatsal60/dev-container-features
The `ociReference` here refers to the collection metadata artifact instead of the individual Features. Hence, the author needs to only add a single entry irrespective of the number of Features that might exist in their repository.

2024-07-30 05:18 UTC, gvatsal60 commented on _data/collection-index.yml
> +- name: pre-commit(via pip)
Sure, Updated the entries

2024-07-30 05:18 UTC, gvatsal60 commented on _data/collection-index.yml
> +  ociReference: ghcr.io/gvatsal60/dev-container-features
Removed one of them.

2024-07-30 15:19 UTC, samruddhikhandale approved these changes
Thanks!

2024-07-30 15:19 UTC, merged