Update collection-index.yml
devcontainers/devcontainers.github.io pull request #446
Opened 2024-08-09 10:48 UTC by igwejk

List demos-by-igwejk/devcontainer-templates/java template

## What type of PR is this?

- [x] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Related Issues

- Related Issue #
- Closes #

## Description

_Please replace this line with a description of your PR._

### Collection checklist
_If your PR contributes a new collection, please utilize this checklist:_
- [x] Collection name
- [x] Maintainer name
- [x] Maintainer contact link (i.e. link to a GitHub repo, email)
- [x] Repository URL
- [x] OCI Reference
- [x] I acknowledge that this collection provides new functionality, distinct from the existing collections part of this index.

2024-08-09 19:14 UTC, samruddhikhandale requested changes

2024-08-09 19:14 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/demos-by-igwejk/devcontainer-templates/java
```suggestion
  ociReference: ghcr.io/demos-by-igwejk/devcontainer-templates
```

Hi 👋 

The `ociReference` here refers to the collection metadata artifact instead of the individual 
templates. Hence, the author needs to only add a single entry irrespective of the number of Templates that might exist in their repository.

Can you help update this? thanks!

2024-08-09 19:14 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/demos-by-igwejk/devcontainer-templates/java
Can you help change the visibility of this "metadata" package (and your Template package) to public? The [index](https://containers.dev/features) won't be able to crawl the Templates in `demos-by-igwejk/devcontainer-templates` if it's private.

Feel free to look at https://containers.dev/guide/author-a-feature#publishing for information.

2024-08-20 05:20 UTC, krishnprakash approved these changes

2025-10-27 17:17 UTC, AlvaroRausell commented
Closing as user did not respond to review comments in over a year

2025-10-27 17:17 UTC, closed without merging