collection-index: Add AIT-Assistive-Autonomous-Systems features
devcontainers/devcontainers.github.io pull request #458
Opened 2024-09-04 11:40 UTC by devrite

## What type of PR is this?

- [x] Add a new dev container collection

## Description
AIT-Assistive-Autonomous-Systems Dev Container Features to the index.

### Collection checklist
_If your PR contributes a new collection, please utilize this checklist:_
- [x]  Collection name
- [x] Maintainer name
- [x] Maintainer contact link (i.e. link to a GitHub repo, email)
- [x] Repository URL
- [x] OCI Reference
- [x] I acknowledge that this collection provides new functionality, distinct from the existing collections part of this index.

2024-09-06 16:55 UTC, samruddhikhandale requested changes, later dismissed

2024-09-06 16:55 UTC, samruddhikhandale commented on _data/collection-index.yml
> +  ociReference: ghcr.io/AIT-Assistive-Autonomous-Systems/devcontainer_features
```suggestion
  ociReference: ghcr.io/ait-assistive-autonomous-systems/devcontainer_features
```

Hi 👋

The ORAS spec requires the `ociReference` to be in lower case. Can we update here, thanks?
The supporting tools do help convert the case, however, its better to sync as much as possible.

2024-09-10 05:34 UTC, devrite commented on _data/collection-index.yml
> +  ociReference: ghcr.io/AIT-Assistive-Autonomous-Systems/devcontainer_features
Hi,
updated.

2025-02-26 13:25 UTC, devrite commented
@samruddhikhandale Any updates from my side required?

2025-10-27 17:18 UTC, AlvaroRausell commented
Hi @devrite, I am unable to pull from main and/or resolve the conflicts, would you be able to give me permissions to push this through please? Thank you!

2025-10-29 04:12 UTC, devrite commented
@AlvaroRausell Seems like the checkbox for making maintainers being able to make edits is missing. I will try to update when I get the chance.

2025-11-20 12:35 UTC, AlvaroRausell approved these changes

2025-11-20 12:35 UTC, AlvaroRausell approved these changes

2025-11-20 12:36 UTC, merged