chore: add atomys collection
devcontainers/devcontainers.github.io pull request #489
Opened 2024-10-18 10:28 UTC by 42atomys

## What type of PR is this?

- [x] Add a new dev container collection
- [ ] Update to an existing dev container collection
- [ ] Documentation/spec update
- [ ] Other containers.dev site update (UX, layout, etc)

## Description

I currently start to update and create a collection of features missing on the index like dragonfly, meilisearch and more. So I add it to the index for everyone :) 

### Collection checklist
_If your PR contributes a new collection, please utilize this checklist:_
- [x] Collection name
- [x] Maintainer name
- [x] Maintainer contact link (i.e. link to a GitHub repo, email)
- [x] Repository URL
- [x] OCI Reference
- [x] I acknowledge that this collection provides new functionality, distinct from the existing collections part of this index.

2025-02-21 16:08 UTC, Kaniska244 commented
Thanks for the PR!
Change approved This can be merged.

2025-02-21 16:10 UTC, Boomtokn approved these changes

2025-02-24 17:07 UTC, eljog commented
PR looks good.
Could you please resolve the conflicts @42atomys ?

2025-02-25 11:18 UTC, 42atomys commented
@eljog Thanks for pining me, all is good ✅

2025-07-29 00:06 UTC, 42atomys commented
@eljog Hi, do you have any updates for me ? 🙏 

Thanks in advance

2025-11-07 06:34 UTC, Kaniska244 requested changes

2025-11-07 06:34 UTC, Kaniska244 commented on _data/collection-index.yml
> +  ociReference: ghcr.io/42atomys/devcontainers-featuresz
@42atomys  This oci reference is returning 404. Would you kindly setup the collection in ghcr.

2025-11-07 17:53 UTC, 42atomys commented on _data/collection-index.yml
> +  ociReference: ghcr.io/42atomys/devcontainers-featuresz
@Kaniska244 Don't got the `z` I have added on last conflict resolving !
This is fixed

2025-11-10 04:40 UTC, Kaniska244 approved these changes
Change looks fine. To be further reviewed by maintainers.

2025-11-20 12:37 UTC, AlvaroRausell approved these changes

2025-11-20 12:37 UTC, merged